version: '3.8'

services:
  ggpoker:
    build: .
    ports:
      - "3000:3000"  # P2P server
      - "3001:3001"  # API server
      - "5173:5173"  # Web interface
    environment:
      - WHOP_API_KEY=${WHOP_API_KEY}
      - WHOP_PRODUCT_ID=${WHOP_PRODUCT_ID}
      - WHOP_WEBHOOK_SECRET=${WHOP_WEBHOOK_SECRET}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for session management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Optional: PostgreSQL for persistent data
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ggpoker
      POSTGRES_USER: poker
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-poker123}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
